"""Add unique into name

Revision ID: 0f54851baa58
Revises: e9f9c3677743
Create Date: 2025-12-30 16:45:45.963186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f54851baa58'
down_revision: Union[str, Sequence[str], None] = 'e9f9c3677743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == 'sqlite':
        with op.batch_alter_table('complex') as batch_op:
            batch_op.create_unique_constraint('uq_complex_name', ['name'])
        with op.batch_alter_table('user') as batch_op:
            batch_op.create_unique_constraint('uq_user_name', ['name'])
    else:
        op.create_unique_constraint(None, 'complex', ['name'])
        op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'complex', type_='unique')
    # ### end Alembic commands ###
