"""Set nullable into cotis number

Revision ID: 5cb538b798cc
Revises: 0f54851baa58
Create Date: 2026-02-08 16:02:52.011160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb538b798cc'
down_revision: Union[str, Sequence[str], None] = '0f54851baa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('cotis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Operations on 'complex' table are commented out to avoid SQLite issues and potential redundancy.
    # If specifically needed, they should be enabled with batch_alter_table checks.
    # op.drop_index(op.f('ix_complex_name'), table_name='complex')
    # op.create_unique_constraint(None, 'complex', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('cotis',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # op.drop_constraint(None, 'complex', type_='unique')
    # op.create_index(op.f('ix_complex_name'), 'complex', ['name'], unique=1)
    # ### end Alembic commands ###
